Use certificate for production HaalCentraal
Amsterdam/dso-api pull request #169
Opened 2021-01-20 15:39 UTC by bheupers

Explicit filter kadastrale objecten for natuurelijk persoon if not
BRK/RSN.

Use schema only for validation of response, but return complete
HaalCentraal response

# This Pull request contains changes to:

<Please fill information>

# In case changes new features added

- [ ] Customer friendly documentation added into `docs/`.
- [ ] Developer friendly documentation added into `DEVELOPMENT|README.md`

# In case breaking changes introduced into API

- [ ] There is customer notification plan: ....

# In case this PR reverts changes in repo

- [ ] Extraq details describing reasoning: ...

2021-01-22 08:20 UTC, vdboor requested changes

2021-01-22 08:20 UTC, vdboor commented on src/dso_api/dynamic_api/remote/views.py
> +        if self.dataset_id == "hcbrk":
Dit lijkt me niet echt wenselijk toch?

2021-01-22 08:20 UTC, vdboor commented on src/dso_api/dynamic_api/remote/views.py
> +                            data["_embedded"][k] = new_ldata
Dit gaat straks stuk als we responses streaming maken. Kan er niet op serializer niveau iets gedaan worden? Nu wordt er middleware-achtig naderhand wat aangepast.

2021-01-22 08:20 UTC, vdboor commented on src/dso_api/dynamic_api/remote/views.py
> +        if request.method != "OPTIONS" and not request.is_authorized_for("BRK/RSN"):
is hier een generieke wijze voor te vinden?

2021-01-22 08:21 UTC, vdboor requested changes

2021-01-22 08:21 UTC, vdboor commented on src/dso_api/dynamic_api/remote/views.py
> +            return filtered_data
Is hier een generieke wijze voor te vinden?

2021-01-25 10:40 UTC, bheupers commented
Voorlopig alleen wijziging om certificaat te gebruiken om HaalCentraal productie te kunnen gebruiken. Dat moet dan wel met BRK/RSN (specialen medewerker) scope

2021-02-16 13:07 UTC, merged