WIP. camelCase checks in WFS.
Amsterdam/dso-api pull request #208
Opened 2021-02-25 12:44 UTC by ngaranko

# This Pull request contains changes to:

Fixes issue with WFS authorization.

# In case changes new features added

- [ ] Customer friendly documentation added into `docs/`.
- [ ] Developer friendly documentation added into `DEVELOPMENT|README.md`

# In case breaking changes introduced into API

- [ ] There is customer notification plan: ....

# In case this PR reverts changes in repo

- [ ] Extra details describing reasoning: ...

2021-02-25 15:41 UTC, vdboor commented on src/tests/test_dynamic_api/test_views_wfs.py
> +        response_text = "".join([line.decode("utf-8") for line in response.streaming_content])
```suggestion
        response_text = read_response(response)
```

en bovenaan `from tests.utils import read_response

2021-02-25 15:52 UTC, vdboor commented on src/tests/test_dynamic_api/test_views_wfs.py
> +            data[x.tag.split("}")[1]] = x.text
Dit naar een functie toe (DRY).

`return {key: value for element in element}

2021-02-25 15:53 UTC, vdboor approved these changes
Gezien de ernst, lekker committen! Tests kunnen mooier maar zijn conceptueel erg fraai opgezet!

2021-02-25 15:57 UTC, vdboor commented on src/dso_api/dynamic_api/views/wfs.py
> +            if snake_to_camel_case(model_field.name) in unauthorized_fields:
Er zijn meer plekken (expanded fields) waar deze check nog stuk is!

2021-02-25 15:57 UTC, vdboor requested changes
Checks werken nog niet voor expanded fields.

2021-02-25 16:21 UTC, cvriel approved these changes
Snel gevonden en opgelost

2021-03-01 09:41 UTC, vdboor approved these changes

2021-03-01 09:47 UTC, merged